#!/bin/bash

ACCOUNT_ID=$AWS_ACCOUNT_ID
REGION=$AWS_DEFAULT_REGION

aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
